"""Minimal iLink transport used by the native WeChat channel."""

from .auth import (
    LoginResult,
    default_accounts_dir,
    download_qr_image,
    fetch_qrcode,
    get_first_credential,
    get_qr_code_dir,
    has_valid_credentials,
    load_all_credentials,
    new_accounts_dir,
    poll_qrcode_status,
    poll_qrcode_until_confirmed,
    remove_all_credentials,
    remove_credentials,
    save_credentials,
)
from .client import ILinkClient
from .media import download_file_item, download_image_item, send_media_from_path, send_text_message
from .monitor import ILinkMonitor
from .types import (
    CDNMediaTypeFile,
    CDNMediaTypeImage,
    CDNMediaTypeVideo,
    Credentials,
    FileItem,
    ImageItem,
    ItemTypeFile,
    ItemTypeImage,
    ItemTypeText,
    ItemTypeVideo,
    MediaInfo,
    MessageItem,
    MessageStateFinish,
    MessageTypeUser,
    TextItem,
    VideoItem,
    WeixinMessage,
)

__all__ = [
    "CDNMediaTypeFile",
    "CDNMediaTypeImage",
    "CDNMediaTypeVideo",
    "Credentials",
    "FileItem",
    "ILinkClient",
    "ILinkMonitor",
    "ImageItem",
    "ItemTypeFile",
    "ItemTypeImage",
    "ItemTypeText",
    "ItemTypeVideo",
    "LoginResult",
    "MediaInfo",
    "MessageItem",
    "MessageStateFinish",
    "MessageTypeUser",
    "TextItem",
    "VideoItem",
    "WeixinMessage",
    "default_accounts_dir",
    "download_file_item",
    "download_image_item",
    "download_qr_image",
    "fetch_qrcode",
    "get_first_credential",
    "get_qr_code_dir",
    "has_valid_credentials",
    "load_all_credentials",
    "new_accounts_dir",
    "poll_qrcode_status",
    "poll_qrcode_until_confirmed",
    "remove_all_credentials",
    "remove_credentials",
    "save_credentials",
    "send_media_from_path",
    "send_text_message",
]
